#!/bin/sh
# Prepend or append stuff onto the i3status output,
# as recommended by man i3status.
# The hell sed-line is inserting the following json entry:
#
#     {"name":"pomodoro","full_text":"12 min"}
#
# Requires the following setting in ~/.i3status.conf.
# In this way we keep the colour formatting of the i3status:
#
#     output_format = i3bar

i3status | while true; do
         read line
         # ,[{"name":"cpu_usage","full_text":"00%"}, ... ,{"name":"time","full_text":"Monday # 03 Dec 2012 12:28PM"}]
         echo $line |
            sed 's#{"name":#{"name":"pomodoro","full_text":"'"$(pomodoro_remaining_time)"'"},&#'
done

